### ISSUE TITLE
Gas inefficient storage of listings

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-marketplace#10]
Listings are currently stored as follows:

```solidity
struct Listing {
    /// @dev amount of tokens for sale. For ERC721 it's always 1.
    uint256 quantity;
    /// @dev price for each token listed. For ERC721 it's the price of sale,
    /// for ERC1155 this price is multiplied by amount of tokens being bought
    uint256 pricePerItem;
    /// @dev timestamp after which the listing is invalid
    uint256 expirationTime;
}
```

In all places that validate this information, each of the three storage locations are read from chain. It would be more efficient to reduce the range of `expirationTime` and `quantity` to store them in the same slot.

We can profile this, but I guess it will save several cents (US current cents, Euro cents, etc.) for each transaction if we do this.

**Recommendation**: consider to combine the storage locations if it is thought that gas costs could ever make this optimization worthwhile.

**Comment by ghoul-sol** [comment]
I think there's no harm in optimizing.
