### ISSUE TITLE
Updating the payment token changes the commitments on behalf of sellers without their consent

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-marketplace#14]
This is a duplicate of https://github.com/ghoul-sol/treasure-marketplace/issues/3 including different thoughts related to the topic.

Contract participants that create a listing will be specifying the payment amount versus a payment token that they can see at the time they submit the transaction.

There are several situations to consider:

1. The payment token could be updated by the owner at the same time as this transaction is happening.
2. The payment token could be updated by the owner after the listing has been active for a while.
3. The payment token could be updated by the owner at the same time as a buyer is purchasing.

Different payment tokens have vastly different values, it is not uncommon to see differences on a factor exceeding the difference between the Earth-Moon distance versus a centimeter.

A seller that set a "to the moon" price will be unhappy to receive only a "centimeter" payment.

Conversely, a buyer executing a "centimeter" payment, will be unhappy to know they spent a "to the moon price".

And most dangerously, if the owner is cooperating with a "hacker", it is possible to steal all customer NFTs and maintain plausible deniability that this was a mistake, rather than a malicious act.

**Recommendations**:

1. If the intent of this function is that the admin will use it rarely and only to update between extremely similar tokens both representing the same thing at the same value... then this commitment should be spelled out in plain text in the contract.
2. When the payment token is changed, all existing offers should be invalidated. (This can be done efficiently.) Or if they are non invalidated, this risk should be very clearly explained in all cases where relevant.

**Comment by fulldecent** [comment]
Please help me understand the situations that are expected where Treasure Marketplace will need to update its payment token. This will help me propose the best solution here.

I am thinking it might be one of these:

## OPTION: "We won't ever change the payment token. If we ever want to, that will be a separate marketplace."

_This makes sense if the payment token is strongly connected with this Treasure Marketplace._

Great, let's remove some of thees dangerous functions.

## OPTION: "We might change the payment token in the future but only as part of a contract upgrade."

Then let's leave some extra gap room in `Listing` and remove the functions from the contract.

P.S. Contract upgrades are dangerous and they are addressed in #8.

## OPTION: "We only expect to ever change the payment token if our payment token is hacked or for reason we need to upgrade it/stake it/bridge it somehow."

Okay, there's two ways this could go. One is that we should invalidate all open orders when the payment token is changed. And Two is that would should migrate all Seller commitments to the new token (as current).

If we will migrate all Seller commitments to the new token, the Sellers are trusting us that we won't migrate to WETH or something else that is wildly different in value than the current payment token. This commitment needs to be spelled out very clearly in documentation.

**Comment by ghoul-sol** [comment]
This was addressed by #34. Closing.
