### ISSUE TITLE
Missing upgradability gap

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-marketplace#20]
This contract is intended to be upgradable. However the storage gap is missing so upgradability will be affected.

For more information, see https://docs.openzeppelin.com/contracts/4.x/upgradeable#storage_gaps

**Recommendation**: calculate the correct gap to the customary total and add as last storage item

**Comment by ghoul-sol** [comment]
Can you expand on a reason why should we add gap to the marketplace contract? To my understanding, gaps are used by OpenZeppelin to give them the flexibility to add new variables in the new version of the library and keep it compatible with new upgrades. In the case of the marketplace, it seems we can just add a new storage variable at the end and expand storage.

**Comment by fulldecent** [comment]
Yes, you can continue to keep adding storage at the end of the contract.

Honestly, I cannot find OZ saying anywhere that concrete contracts like Marketplace should have gaps, or not. OZ should be more clear about that.

But specifically, the only risk for this project would be if a future upgrade makes a subclass of the marketplace, and then you wanted to add storage variables to this current contract and the subclass.

This issue can be closed without action, and there is no risk for the foreseeable future.

**Comment by ghoul-sol** [comment]
Thank you for explaining!
