### ISSUE TITLE
Treasure Marketplace Contract Review ac31264

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-marketplace#25]
Treasure Marketplace Contract Review
William Entriken
Delivered 2022-03-06

Thank you for the opportunity to participate in this code review!

## Review scope

This is a review of Treasure Marketplace, pre-release version. Code was published at https://github.com/ghoul-sol/treasure-marketplace/commit/ac31264ac2973de946dc397d01c2cf8118ce9616 with SHA-1 hash `ac31264ac2973de946dc397d01c2cf8118ce9616`.

The scope of review included code-level review (human reading source code), automated code review, (computer reading source code). Due to limitations of the engagement, the review does not include unit testing (computer running small-scope tests), and functional testing (human using compiled program).

The review was performed for the purpose of comparing Treasure Marketplace against known vulnerabilities of the deployed Treasure Marketplace contract, the plain English meaning of comments and function names, and a general understanding of NFT marketplaces. Any deviation from this standard, or deficiency against relevant best programming practices would be an in-scope review finding.

Sensitivity was set as "anything we should fix or that you wouldn't want a million people to read".

## Review exclusions

Open Zeppelin Contacts were specifically excluded from the scope. Although certain notes about the contracts used are provided below.

Quality and correctness of automated testing approaches and deployment strategy is excluded from the scope.

## Findings

Each finding is listed and is organized by topic. Critical findings that are not resolved are marked with the bomb symbol (💣) and other unresolved material findings are marked with the warning symbol (⚠️). Resolved and less-than-material findings have no emoji marking.

### Undisclosed powers of owner

These findings are related to features that the owner has control over which may pose risks to other users.

[:warning: Owner may frontrun and take 100% of fees](https://github.com/ghoul-sol/treasure-marketplace/issues/5)

[[💣 Owner may steal customer NFTs](https://github.com/ghoul-sol/treasure-marketplace/issues/6)](https://github.com/ghoul-sol/treasure-marketplace/issues/6)

[:warning: Owner can rugpull with upgrade](https://github.com/ghoul-sol/treasure-marketplace/issues/8)

### Marketplace design

These are fundamental design issues. Fixings these will affect the smart contract as well as the front-end application.

[:bomb: Updating the payment token changes the commitments on behalf of sellers without their consent](https://github.com/ghoul-sol/treasure-marketplace/issues/14)

[:bomb: Seller unable to cancel listing](https://github.com/ghoul-sol/treasure-marketplace/issues/15)

[:bomb: Owner can harm sellers by pausing contract](https://github.com/ghoul-sol/treasure-marketplace/issues/16)

[:bomb: Expiration times can be are much longer than specified](https://github.com/ghoul-sol/treasure-marketplace/issues/21)

[[updateListing does not allow to increase price](https://github.com/ghoul-sol/treasure-marketplace/issues/17)](https://github.com/ghoul-sol/treasure-marketplace/issues/17)

[[There is no meaningful difference between createListing and updateListing](https://github.com/ghoul-sol/treasure-marketplace/issues/18)](https://github.com/ghoul-sol/treasure-marketplace/issues/18)

### Implementation details

These findings affect only the smart contract and not any other applications.

[:warning: Package management uses ranges](https://github.com/ghoul-sol/treasure-marketplace/issues/7)

[[Solidity version is unsupported](https://github.com/ghoul-sol/treasure-marketplace/issues/9)](https://github.com/ghoul-sol/treasure-marketplace/issues/9)

[[Gas inefficient storage of listings](https://github.com/ghoul-sol/treasure-marketplace/issues/10)](https://github.com/ghoul-sol/treasure-marketplace/issues/10)

[[Unsemantic reference to payment token](https://github.com/ghoul-sol/treasure-marketplace/issues/12)](https://github.com/ghoul-sol/treasure-marketplace/issues/12)

[[NFT registration could obviate need for using ERC-165 introspection](https://github.com/ghoul-sol/treasure-marketplace/issues/13)](https://github.com/ghoul-sol/treasure-marketplace/issues/13)

[[Opportunities for inlining code](https://github.com/ghoul-sol/treasure-marketplace/issues/19)](https://github.com/ghoul-sol/treasure-marketplace/issues/19)

[:warning: Missing upgradability gap](https://github.com/ghoul-sol/treasure-marketplace/issues/20)

[[Missing unchained initializer](https://github.com/ghoul-sol/treasure-marketplace/issues/22)](https://github.com/ghoul-sol/treasure-marketplace/issues/22)

[[_buyItem implementation is fragile to reentrancy](https://github.com/ghoul-sol/treasure-marketplace/issues/23)](https://github.com/ghoul-sol/treasure-marketplace/issues/23)

https://github.com/ghoul-sol/treasure-marketplace/issues/30

### Code style

There findings relate to only the way that the code is presented.

[:warning: Deprecated wording](https://github.com/ghoul-sol/treasure-marketplace/issues/11)

[[NatSpec documentation is missing](https://github.com/ghoul-sol/treasure-marketplace/issues/4)](https://github.com/ghoul-sol/treasure-marketplace/issues/4)

[[Code does not follow the Solidity style guide](https://github.com/ghoul-sol/treasure-marketplace/issues/24)](https://github.com/ghoul-sol/treasure-marketplace/issues/24)

**Comment by minebuu** [comment]
Respect you. I learned a lot from the issues you submitted.

**Comment by ghoul-sol** [comment]
I believe all finding has been addressed and the issue can be closed.

**Comment by ghoul-sol** [comment]
If anything is missing, feel free to reopen.
