### ISSUE TITLE
Security issue about setPaymentToken function

### ISSUE THREAD

**Issue by minebuu** [ghoul-sol/treasure-marketplace#3]
The contract can change the `paymentToken` using the `setPaymentToken` function by the owner. However, if the payment token will be changed, the listed NFT price will be affected. 

```
  function setPaymentToken(address _paymentToken) public onlyOwner {
        paymentToken = _paymentToken;
        emit UpdatePaymentToken(_paymentToken);
    }
```
For example, assume that I listed a smolBrain at 3000 MAGIC. Then the contract saves the `Listing` structure that has `pricePerItem` is 3000. But the structure doesn't have the information on what token is used. (The actual send is executed in `IERC20Upgradeable(paymentToken).safeTransferFrom(_msgSender(), feeReceipient, feeAmount);` in line 305.)
When the attackers get owner key (very low probability scenario) and change the `paymentToken` using setPayment funtion to some POO token (assume that it is almost 0 value token), then the attacker can buy the smolBrain at 3000 POO token (almost 0 value).  

Because Treasure marketplace only uses $MAGIC token as a currency token and the `setPayment` function is only need to set MAGIC address at once in the initial Phase, input address of MAGIC token as a hardcode rather than use the setPayment function is more secure. 

Therefore my suggestion is to remove the `setPaymentToken` function and then set `  address public paymentToken = 0x539bdE0d7Dbd336b79148AA742883198BBF60342; //MAGIC Token address`  in line 20. (or just use `Init` function) 

This is because setPaymentToken is only needed once, and reusing that function can lead to a fatal attack.

Another solution is to add `paymentToken` variable to `Listing` structure and `createListing` function. Plus, change the line 305.
Maybe the method is more useful to adopt other tokens as a payment currency in Treasure Marketpalce for future possible plan.

**Comment by fulldecent** [comment]
Issue confirmed. You can remove the word "possible" in title.
