### ISSUE TITLE
NatSpec documentation is missing

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-marketplace#4]
[NatSpec](https://docs.soliditylang.org/en/v0.8.6/natspec-format.html#natspec) documentation allows wallets and other Web3 applications to inform a human interacting with the contract what they are about to do. They may see "are you sure you want to call `cancelListing ` with `nftAddress` 0x232398473 and `tokenID` 11" rather than something like "do you want to call `0x5cd346fa` with message data `0x0273eecfb480dcfbab423bd15c71e7ad70c7a9504689ff56edb137a5d37146d6`".

Best practice is to include documentation for all public interfaces and this is recommended by the Solidity project:

> It is recommended that Solidity contracts are fully annotated using [**NatSpec**](https://docs.soliditylang.org/en/v0.8.6/natspec-format.html#natspec) for all public interfaces (everything in the ABI).
>
> https://docs.soliditylang.org/en/v0.8.6/style-guide.html?highlight=natspec

**Recommendation**: implement NatSpec for every public, internal, and external function and use all possible detail in NatSpec.

**Comment by ghoul-sol** [comment]
Docs added
