### ISSUE TITLE
Owner may frontrun and take 100% of fees

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-marketplace#5]
In the `_buyItem` function (usable externally from `buyFrom` function) fee is calculated using the `fee` variable.

The effective fee that a trade will settle for is not known by the buyer at the time of the transaction. Due to transaction settlement reordering the fee may be changed using `setFee` between the time that the buyer makes a purchase and when it settles.

The risk is that before a high value transaction is committed (and additionally, any transactions that have been started but have been left sitting in the mempool) can be sandwiched by the owner to take 99.99% of the proceeds.

Yes, there is a reputational hit for the owner if they perform this rugpull. However the owner can benefit if:

1. There is a wide variety of product prices on the marketplace;
2. The normal fee is low
3. Ownership is handled by a multisig wallet or DAO
4. Ownership includes plausible deniability/anonymity

**Recommendation**: use a two-step method to execute fee changes

**Comment by fulldecent** [comment]
Additional risk if parlayed with https://github.com/ghoul-sol/treasure-marketplace/issues/3: 

The owner may cause any transaction to change to WETH (which is significantly more valuable than MAGIC) and change the fee amount at the same time.

This satisfies conditions 1. and 2. and makes this attack feasible.

**Comment by fulldecent** [comment]
Please help me understand the situations that are expected where Treasure Marketplace will change the fee amount. This will help me propose the best solution here.

If you can tell me that the fee will never go above a certain amount (5%? 10%? 20%?) then we can hardcode that into the smart contract. That will be better than the current number which is 99.99%.

If the number is "low" and "reasonable" like 5% or 10% then the fix is easy. But if the limit will be higher then we should disclose this risk to sellers and maybe give them other protections.

**Comment by ghoul-sol** [comment]
The team decided to limit the fee to 15%. I think this will be the easiest fix.
