### ISSUE TITLE
[L02] Payment toke address can be 0

### ISSUE THREAD

**Issue by ghoul-sol** [ghoul-sol/treasure-marketplace#50]
https://github.com/ghoul-sol/treasure-marketplace/blob/06dba996a7b6e4db7a242d49f2b149fb6db9e5fa/contracts/TreasureMarketplace.sol#L141
Payment token address can be set to 0 which would result in the marketplace reverting on all buy transactions.

**Comment by fulldecent** [comment]
This should be caught during burn-in testing before public announcement. Adding this extra safety check won't hurt anything.
