### ISSUE TITLE
[L03] Implementation contract can be initialised by anyone

### ISSUE THREAD

**Issue by ghoul-sol** [ghoul-sol/treasure-marketplace#51]
https://github.com/ghoul-sol/treasure-marketplace/blob/06dba996a7b6e4db7a242d49f2b149fb6db9e5fa/contracts/TreasureMarketplace.sol#L128

The implementation contract can be initialised by anyone calling the initialize function. Although harmless in this instance, the implementation contract should be always initialise in its own constructor.

ref: https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#initializing_the_implementation_contract

**Comment by fulldecent** [comment]
Any problem here should be caught by the burn-in testing prescribed at https://github.com/ghoul-sol/treasure-marketplace/blob/06dba996a7b6e4db7a242d49f2b149fb6db9e5fa/contracts/TreasureMarketplace.sol#L123-L124.

**Comment by TSnark** [comment]
My understanding is that the comment refers to the proxy contract, my comments was towards the implementation contract. 
Of course the proxy initialisation is a critical operation, my suggestion in this instance is a nice to have as we don't have nested delegated calls. In other cases it can be dangerous:

https://blog.trailofbits.com/2020/12/16/breaking-aave-upgradeability/
