### ISSUE TITLE
Consider adding fat finger protection

### ISSUE THREAD

**Issue by ghoul-sol** [ghoul-sol/treasure-marketplace#53]
https://github.com/ghoul-sol/treasure-marketplace/blob/06dba996a7b6e4db7a242d49f2b149fb6db9e5fa/contracts/TreasureMarketplace.sol#L218

This could be achieved with a minimum price by collection and a force parameter to override it.

**Comment by ghoul-sol** [comment]
We'll require `_pricePerItem > 1e9`

**Comment by jcheese1** [comment]
We've got a modal confirming if its lower than floor price AND a floor price indicator if a user inputs a value lower than floor, haha.
