### ISSUE TITLE
Deployment scripts not standard

### ISSUE THREAD

**Issue by ghoul-sol** [ghoul-sol/treasure-marketplace#55]
https://github.com/ghoul-sol/treasure-marketplace/tree/06dba996a7b6e4db7a242d49f2b149fb6db9e5fa/deploy

Deployment scripts do not follow best practice of one idempotent action per script and partition by network should be avoid in the spirit of testing the deployment pipeline as is.
Proxy deployment seems missing.

**Comment by treasure-t1dev** [comment]
acceptable risk for this round of audits. Will circle back after re-opening marketplace to discuss/seek help for best practices and implementation.
