### ISSUE TITLE
Naming conventions 

### ISSUE THREAD

**Issue by ghoul-sol** [ghoul-sol/treasure-marketplace#56]
Prefer prefix _ for internal and private members and postfix _ for clashing function parameters.
Events naming is inconsistent. Prefer using past tense for event naming.

**Comment by fulldecent** [comment]
The only internal member is `_createListingWithoutEvent` and it is underscore prefixed.

There are no private members.

Please clarify what change is preferred.

---

I agree that event naming could be improved.

**Comment by TSnark** [comment]
Let me premise this gets more into personal taste. Buy using postfix _ for function parameters removes one source of ambiguity when reading a symbol. To be explicit I mean:
- No underscore, public members
- Prefix underscore: private and internal members
- Postfix underscore: function params

i.e. https://github.com/ghoul-sol/treasure-marketplace/blob/06dba996a7b6e4db7a242d49f2b149fb6db9e5fa/contracts/TreasureMarketplace.sol#L151

_nft -> nft_

**Comment by ghoul-sol** [comment]
We are keeping the interface unchanged on purpose to limit changes on other parts of the stack.

Regarding a naming convention, I'd prefer to push it for the next version.
