### ISSUE TITLE
One test case should strive to test one invariant/post condition. Current test cases test too many things.

### ISSUE THREAD

**Issue by ghoul-sol** [ghoul-sol/treasure-marketplace#58]

**Comment by fulldecent** [comment]
I agree that more `it`s could be used to separate testing.

**Comment by ghoul-sol** [comment]
That's true. We'll work on improvement for test readability in the future. On the bright side, test coverage is pretty good.

**Comment by fulldecent** [comment]
You're being modest... test coverage literally can't get any better than 100% which is what you have :-)
