### ISSUE TITLE
Package management uses ranges

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-marketplace#7]
In the package versions, vendor packages are checked using a range string. https://github.com/ghoul-sol/treasure-marketplace/blob/cf27ad491276b0a833d229949e3237b5e13506f2/package.json#L18

This creates a risk that during deployment you will use a different version of upstream packages than what has been audited.

**Recommendation**: pin a specific version in this repository for all contract sources (Solidity) and vendor requirements.

**Comment by ghoul-sol** [comment]
Fixed OZ versions
