### ISSUE TITLE
Owner can rugpull hard with upgrade

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-marketplace#8]
This contract is using upgradable logic. This means that the owner can deploy a new contract at any time and take every NFT and all authorized payment tokens owned by everybody that has listed NFTs for sale on the marketplace.

This may be an economically feasible rugpull strategy. And the feasibility of this rugpull increases as time goes on.

Such a risk may not be obvious to participants of the smart contract. And so for them this is an unknown risk.

**Recommendation**: this risk should be explicitly disclosed at the top of the contract (in a `@notice` or `@dev` NatSpec entry) and in any documentation for people using the contract.

**Comment by ghoul-sol** [comment]
This is mitigated twofold:

- [ ] Proxy owner is transferred to dev's multisig controlled by multiple people
- [ ] A comment has been added to natspec explicitly saying that the contract is upgradable and governed by the project's multisig

**Comment by fulldecent** [comment]
Strong warning language is added in `fix-everything` at end.
